### ISSUE TITLE
kartta-app.js and kartta-app.css are missing

### ISSUE THREAD

**Issue by nathalie** [kartta-labs/mapwarper#15]
Hi, 
I'm trying to setup my own instance with docker-compose. I got the server running in production mode, but when I go to the login page, I see requests http://localhost:3000/assets/kartta-app.js failing with 404. Same for the css file.
Should I build this in some way, or can I get it from a public location? It is not included in the source.
Thanks!

**Comment by rkversion** [comment]
Nathalie, this version of MapWarper is not really a standalone application. 
The files that you are missing are at https://github.com/kartta-labs/Project/tree/master/public/assets but there is a lot more that 
is also missing (login/authentication 1st comes to mind)
So if you you want to set up your own instance, you should start with the instructions here https://github.com/kartta-labs/Project
